name = "r2-worker-proxy"
main = "src/index.ts"
compatibility_date = "2024-06-16"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[[r2_buckets]]
binding = "R2_BUCKET_NAME"
bucket_name = "service-app"                       # production bucket
preview_bucket_name = "r2-worker-proxy-preview"   # preview bucket

# D1 database binding (used for general rate limiting)
[[d1_databases]]
binding = "DB"
database_name = "ratelimite"
database_id = "bcc9a1eb-e1e5-4d34-a302-5de8d45d0b99"  


[observability]
enabled = true
head_sampling_rate = 1 
